name: 🥒 Ingredient price scanner 💰

on:
  schedule:
    - cron:  '0 0 * * *'  # This will run the action every day at midnight
  workflow_dispatch: # Can also be triggered manually if needed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run update script
      run: node ./path/to/your/script.js
      env:
        DB_URI: ${{ secrets.MONGO_URI }}
        API_KEY: ${{ secrets.KASSALAPP_API_KEY }}
